<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Trapizoidalf" Id="{e2e8732f-1814-4905-ac72-aa316cb52a81}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Trapizoidalf
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Trapizoidalf">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>